### ISSUE TITLE
Feature Request: Logging

### ISSUE THREAD

**Issue by quamina-gladstone** [Terminal-Wallet/terminal-wallet-cli#1]
Sometimes the wallet app dies with no error message, it is extremely difficult to debug.

It would be helpful to have a log file where logs and fatal errors would be written to by the app.

**Comment by linkismissing** [comment]
If you could describe the actions taken prior to the crash that also could be helpful. 

Logging things can potentially log specific data where it shouldn't be, not opposed; just unsure of the happy medium.

If you're manually debugging, you can comment/disable the console.clear() actions and the clearConsoleBuffer() function and everything will print verbose in the console window.
