### ISSUE TITLE
Bug: `invalid BytesLike value`

### ISSUE THREAD

**Issue by jtriley-eth** [Terminal-Wallet/terminal-wallet-cli#4]
entering a password when creating a wallet returns the following.

```
invalid BytesLike value (argument="salt", value="<omitted>", code=INVALID_ARGUMENT, version=6.7.6)
```

useful info:

- fresh download
- `release-1.1.5-linux`
- `rm -r ~/.zKeyChains/` (#3) did not fix
- ubuntu 23.04

**Comment by linkismissing** [comment]
Okay got it! 
Quick fix for now, would be to prefix the value you omitted with '0x' inside the plasma file (inside .zKeyChains/)
it should then look like:
`
{ 
    "name": ".plasma_0",
    "salt": "0x<omitted>"
}
`
